---
- name: Install GNOME with X.Org and enable RDP on Rocky Linux
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install GNOME desktop (disable EPEL/RPMFusion to avoid broken deps)
      ansible.builtin.command: >
        dnf groupinstall "Server with GUI" --disablerepo=epel,rpmfusion-free-updates -y
      register: gnome_install
      changed_when: "'Complete!' in gnome_install.stdout or gnome_install.rc == 0"
      failed_when: gnome_install.rc != 0

    - name: Ensure GDM is installed
      ansible.builtin.dnf:
        name: gdm
        state: present

    - name: Force GNOME to use X.Org system-wide via GDM
      ansible.builtin.blockinfile:
        path: /etc/gdm/custom.conf
        block: |
          [daemon]
          WaylandEnable=false
          DefaultSession=gnome-xorg.desktop
        create: yes
        mode: '0644'

    - name: Set system to boot to graphical target
      ansible.builtin.systemd:
        name: graphical.target
        enabled: true

    - name: Enable and start GDM display manager
      ansible.builtin.systemd:
        name: gdm
        enabled: true
        state: started

    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install EPEL release
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install xrdp
      ansible.builtin.dnf:
        name: xrdp
        state: present

    - name: Enable and start xrdp service
      ansible.builtin.systemd:
        name: xrdp
        enabled: true
        state: started
